# Generated by Django 4.1.7 on 2023-03-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipemodel_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], null=True),
        ),
    ]
