# Generated by Django 4.1.7 on 2023-03-29 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='diet',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\d+(?:,\\d+)*$', 'Enter comma-separated numbers only.')]),
        ),
    ]
