# Generated by Django 4.1.7 on 2023-04-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipemodel_meal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stepmediamodel",
            name="step_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="recipes.stepmodel",
            ),
        ),
    ]
